# Generated by Django 6.1.1 on 2026-09-15 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_language_occupation_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('AWARENESS', 'Awareness'), ('EMERGENCY_ALERT', 'Emergency Alert'), ('EDUCATIONAL', 'Educational'), ('ORGANIZATIONAL_ANNOUNCEMENT', 'Organizational Announcement')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='campaigncontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='audiencesegment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='channel',
            field=models.CharField(default='EMAIL', help_text='EMAIL, SMS, WHATSAPP, PUSH, WEB, SOCIAL, or ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipient',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipient',
            name='consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='external_reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='recipient',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='recipient',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_recipients', to='api.language'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('LOGIN_FAILED', 'Login Failed'), ('RECIPIENT_IMPORT', 'Recipient Import'), ('RECIPIENT_CREATED', 'Recipient Created'), ('AUDIENCE_CREATED', 'Audience Created'), ('CAMPAIGN_CREATED', 'Campaign Created'), ('CAMPAIGN_VALIDATED', 'Campaign Validated'), ('CAMPAIGN_SCHEDULED', 'Campaign Scheduled'), ('CAMPAIGN_DISPATCHED', 'Campaign Dispatched'), ('CAMPAIGN_CANCELLED', 'Campaign Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(default='AWARENESS', help_text='AWARENESS, EMERGENCY_ALERT, EDUCATIONAL, ORGANIZATIONAL_ANNOUNCEMENT', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='channels',
            field=models.JSONField(default=list, help_text="List of channels e.g. ['EMAIL', 'SMS', 'WHATSAPP', 'PUSH', 'WEB', 'SOCIAL']"),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY_FOR_REVIEW', 'Ready for Review'), ('VALIDATED', 'Validated'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_languages',
            field=models.JSONField(default=list, help_text="List of language codes e.g. ['en', 'hi', 'kn', 'ta', 'te']"),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='preferred_channel',
            field=models.CharField(default='EMAIL', help_text='EMAIL, SMS, WHATSAPP, PUSH, WEB, SOCIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='template',
            name='body_template',
            field=models.TextField(help_text='Supports {{title}}, {{message}}, {{location}}, {{date}}'),
        ),
        migrations.AlterField(
            model_name='template',
            name='default_languages',
            field=models.JSONField(blank=True, default=list, help_text="List of language codes e.g. ['en', 'hi', 'kn', 'te', 'ta']"),
        ),
        migrations.CreateModel(
            name='AudienceSegmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(help_text='state, district, language, occupation, status, gender, city, etc.', max_length=50)),
                ('operator', models.CharField(choices=[('=', 'Equals'), ('!=', 'Not Equals'), ('contains', 'Contains'), ('in', 'In')], default='=', max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.audiencesegment')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAudience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('audience_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_audiences', to='api.audiencesegment')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_audiences', to='api.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'audience_segment')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='audiences',
            field=models.ManyToManyField(blank=True, related_name='associated_campaigns', through='api.CampaignAudience', to='api.audiencesegment'),
        ),
        migrations.CreateModel(
            name='CampaignSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(choices=[('SEND_NOW', 'Send Now'), ('SCHEDULED', 'Scheduled')], default='SCHEDULED', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_schedule', to='api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ContentLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='General', help_text='Dengue Prevention, Flood Safety, Public Health, Water Conservation, Education Scholarship, Emergency Preparedness', max_length=100)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_library_items', to='api.language')),
            ],
            options={
                'verbose_name_plural': 'Content libraries',
            },
        ),
        migrations.AddField(
            model_name='recipient',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='api.country'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='api.district'),
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('unit_type', models.CharField(default='Department', help_text='Department, Unit, Team', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.organization')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='api.organizationunit')),
            ],
        ),
        migrations.AddField(
            model_name='recipient',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='api.organizationunit'),
        ),
        migrations.CreateModel(
            name='RecipientEngagementEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(default='EMAIL', max_length=20)),
                ('event_type', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('RESPONDED', 'Responded'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='SENT', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_events', to='api.campaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to='api.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='api.country')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.state'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='api.state'),
        ),
        migrations.CreateModel(
            name='RecipientChannelPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push'), ('WEB', 'Web'), ('SOCIAL', 'Social')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('consent_given_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_preferences', to='api.recipient')),
            ],
            options={
                'unique_together': {('recipient', 'channel')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'state')},
        ),
    ]
