# Generated by Django 6.1.1 on 2026-09-27 12:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_campaigntype_country_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='provider',
            field=models.CharField(db_index=True, default='development', max_length=50),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push Notification'), ('WEB', 'Web Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('CLICKED', 'Clicked'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], db_index=True, default='QUEUED', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='deliverylog',
            unique_together={('campaign', 'recipient', 'channel')},
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('MESSAGE_QUEUED', 'Queued'), ('MESSAGE_PROCESSING', 'Processing'), ('MESSAGE_SENT', 'Sent'), ('MESSAGE_DELIVERED', 'Delivered'), ('MESSAGE_READ', 'Read'), ('MESSAGE_CLICKED', 'Clicked'), ('MESSAGE_FAILED', 'Failed'), ('MESSAGE_RETRIED', 'Retried'), ('MESSAGE_CANCELLED', 'Cancelled')], db_index=True, max_length=30)),
                ('provider_event_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.deliverylog')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
