# Generated by Django 6.1.1 on 2026-09-28 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_deliverylog_clicked_at_deliverylog_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='local', help_text='local, google, etc.', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET_REQUEST', 'Password Reset Request'), ('LOGIN_FAILED', 'Login Failed'), ('ACCOUNT_CREATED', 'Account Created'), ('PROFILE_UPDATED', 'Profile Updated'), ('PREFERENCES_UPDATED', 'Preferences Updated'), ('GOOGLE_LINKED', 'Google Account Linked'), ('EMAIL_VERIFIED', 'Email Verified'), ('RECIPIENT_IMPORT', 'Recipient Import'), ('RECIPIENT_CREATED', 'Recipient Created'), ('AUDIENCE_CREATED', 'Audience Created'), ('CAMPAIGN_CREATED', 'Campaign Created'), ('CAMPAIGN_VALIDATED', 'Campaign Validated'), ('CAMPAIGN_SCHEDULED', 'Campaign Scheduled'), ('CAMPAIGN_DISPATCHED', 'Campaign Dispatched'), ('CAMPAIGN_CANCELLED', 'Campaign Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CAMPAIGN_MANAGER', 'Campaign Manager'), ('COMMUNICATION_TEAM', 'Communication Team'), ('COMMUNICATION_OFFICER', 'Communication Officer'), ('CONTENT_CREATOR', 'Content Creator'), ('ANALYST', 'Analyst')], default='CAMPAIGN_MANAGER', help_text='Role determining permissions across the platform', max_length=50),
        ),
        migrations.CreateModel(
            name='UserCommunicationPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('campaign_updates', models.BooleanField(default=True)),
                ('delivery_alerts', models.BooleanField(default=True)),
                ('ai_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('marketing_announcements', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('designation', models.CharField(blank=True, default='', help_text='Designation / Job Title', max_length=150)),
                ('bio', models.TextField(blank=True, default='', help_text='Creator biography / about')),
                ('organization_name', models.CharField(blank=True, default='', max_length=200)),
                ('organization_type', models.CharField(blank=True, default='Government Department', max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('role_title', models.CharField(blank=True, default='Communication Coordinator', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('primary_language', models.CharField(default='English', max_length=50)),
                ('additional_languages', models.JSONField(blank=True, default=list)),
                ('preferred_channels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
